### ISSUE TITLE
How to set up the queryset?

### ISSUE THREAD

**Issue by yn-coder** [bashu/django-filters-mixin#3]
I have `class SomeListView(FilterMixin, django_filters.views.FilterView)`, 

How can I set up the queryset depend on some request parameters? Something like 
`self.filterset_class = ProductFilterSet( self.request.GET , queryset=Model.objects.filter( field = request['param_name'] ) )`

**Comment by yn-coder** [comment]
Василий, здесь ли вы?

**Comment by bashu** [comment]
момент....

**Comment by yn-coder** [comment]
Если по русски - я задаю датасет, на который уже наложено некоторое условие. В случае обычного def view(request) это делается просто. А как делать в случае generic view?

**Comment by bashu** [comment]
Hi,
check this https://github.com/alex/django-filter/blob/develop/django_filters/views.py#L35 and either override `get_filterset_kwargs` or `get_queryset`, for example:

``` python
def get_filterset_kwargs(self, filterset_class):
   ...
   try:
       kwargs.update({
           'queryset': self.get_queryset().filter(field=self.request['param_name']),
       })
   except ImproperlyConfigured:
   ...
```

**Comment by bashu** [comment]
or here https://github.com/alex/django-filter/blob/develop/django_filters/views.py#L58

``` python
def get(self, request, *args, **kwargs):
    ...
    self.object_list = self.filterset.qs  # *apply filter here*
    ...
```

**Comment by yn-coder** [comment]
get overriding is working fine.

thank you!
