### ISSUE TITLE
ModuleNotFoundError: No module named 'currencies'

### ISSUE THREAD

**Issue by Tuumke** [bashu/django-filters-mixin#6]
I tried to run the example script.
git clone https://github.com/bashu/django-filters-mixin.git
cd django-filters-mixin
virtualenv example
example\Scripts\activate.bat
pip install -r example/requirements.txt
example\Scripts\deactivate.bat
python example/manage.py migrate

`D:\djangofiltermixin\django-filters-mixin>python example/manage.py migrate
Traceback (most recent call last):
  File "example/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'currencies'`

bit it is installed i think?

`D:\djangofiltermixin\django-filters-mixin>example\Scripts\activate.bat

(example) D:\djangofiltermixin\django-filters-mixin>pip install django-currencies
Requirement already satisfied: django-currencies in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (0.9.0)
Requirement already satisfied: jsonfield>=1.0.3 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from django-currencies) (2.0.2)
Requirement already satisfied: django>=1.8 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from django-currencies) (2.1.7)
Requirement already satisfied: requests>=2.14.2 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from django-currencies) (2.21.0)
Requirement already satisfied: bs4 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from django-currencies) (0.0.1)
Requirement already satisfied: pytz in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from django>=1.8->django-currencies) (2018.9)
Requirement already satisfied: idna<2.9,>=2.5 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from requests>=2.14.2->django-currencies) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from requests>=2.14.2->django-currencies) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from requests>=2.14.2->django-currencies) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from requests>=2.14.2->django-currencies) (3.0.4)
Requirement already satisfied: beautifulsoup4 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from bs4->django-currencies) (4.7.1)
Requirement already satisfied: soupsieve>=1.2 in d:\djangofiltermixin\django-filters-mixin\example\lib\site-packages (from beautifulsoup4->bs4->django-currencies) (1.8)

(example) D:\djangofiltermixin\django-filters-mixin>example\Scripts\deactivate.bat`

**Comment by bashu** [comment]
> ...
> example\Scripts\deactivate.bat
> python example/manage.py migrate

why did you deactivate virtualenv before running migrate command? you are supposed to run commands in activated virtual environment

**Comment by bashu** [comment]
@Tuumke I wrote this mixin to use django-filters together with old django-sorting app, but it's obsolete now I guess. for ref https://github.com/carltongibson/django-filter/issues/13
